name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'

    - name: Get dependencies
      working-directory: ./flutter_source
      run: flutter pub get

    - name: Analyze code
      working-directory: ./flutter_source
      run: flutter analyze --no-fatal-infos

    - name: Run tests
      working-directory: ./flutter_source
      run: flutter test || echo "Tests failed but continuing with deployment"

    - name: Build web
      working-directory: ./flutter_source
      run: flutter build web --release --base-href "/"

    - name: Verify build
      working-directory: ./flutter_source
      run: |
        if [ ! -d "build/web" ]; then
          echo "Build directory not found!"
          exit 1
        fi
        if [ ! -f "build/web/index.html" ]; then
          echo "index.html not found in build!"
          exit 1
        fi
        echo "Build verification successful"
        ls -la build/web/

    - name: Copy build to root
      run: |
        # Remove existing files except .git, source, and .github
        find . -maxdepth 1 -not -name '.git' -not -name 'flutter_source' -not -name '.github' -not -name '.' -not -name '.gitignore' -not -name 'README.md' -exec rm -rf {} \; 2>/dev/null || true
        # Copy build output to root
        cp -r flutter_source/build/web/* .
        # Create .nojekyll file for GitHub Pages
        touch .nojekyll
        # List files for debugging
        ls -la

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4